challenges.superman=Superman
challenges.superman_desc=With great power comes great responsibility.\n\n- All physical damage the hero deals is _3 times_ increased.\n- Evasion rate is _3 times_ and accuracy is _2 times_ increased.\n- You start with maximum health of _10_ and does not increase with level.
challenges.pyro=Pyromaniac
challenges.pyro_desc=Fire is one of the greatest blessings given to humans... but sometimes it can also be a disaster.\n\n- Every physical attack made by the hero always sets the enemy on fire._.\n- The duration of effects provided by Fire Imbue and Dragon's Blood Flasks is reduced by _-50%_.
challenges.cursed_dungeon=Cursed Dungeon
challenges.cursed_dungeon_desc=The spirits of the enemies you defeat attack you...\n\n- When you defeat an enemy, _a wraith sometimes appears in its place_.
challenges.fatigue=Fatigue
challenges.fatigue_desc=Continuing combat makes the hero tired...\n\n- Fatigue accumulates every time the hero lands a physical attack or receives a physical attack, and when it accumulates above a certain level, he/she receives a random _negative effect_ briefly. , fatigue is slightly relieved.\n- Fatigue gradually disappears over time, and can be eliminated immediately by eating or using effects that remove negative effects.\n\n- Negative effects that can occur when fatigue accumulates are as follows:.\n\n- Common: _Blind_ by 5 turns\n- Slightly Rare: _Weakened_ by 5 turns or _Daze_ by 5 turns\n- Rare: _Crippled_ by 5 turns or _Vulnerable_ by 5 turns\n- Very Rare: _Paralyzed_ 2 turns or _slow_ 5 turns
challenges.mutation=Mutation
challenges.mutation_desc=The wounds you inflict on enemies mutate them!\n\n- Each time you physically attack an enemy, you'll sometimes turn that enemy into a different enemy.\n\n- The type of enemy you turn into is determined by the region you're on.

seedfinder.cursed=cursed
seedfinder.scrolls=scroll
seedfinder.potions=potion
seedfinder.equipment=equipment
seedfinder.rings=ring
seedfinder.artifacts=artifact
seedfinder.wands=wand
seedfinder.for_sales=store
seedfinder.others=misc
seedfinder.sad_ghost_reward=Sad Ghost's Quest Reward
seedfinder.wandmaker_need=Item what Old Wandmaker requires
seedfinder.wandmaker_reward=Old Wandmaker's Quest Reward
seedfinder.imp_reward=Ambitious Imp's Quest Reward
seedfinder.result=Items of the seed [ %1$s ]( %2$d )
seedfinder.floor=Floor
seedfinder.corpsedust=corpse dust
seedfinder.embers=elemental embers
seedfinder.rotberry=seed of rotberry

badges$badge.unlock_gunner.title=Gunner Unlocked!
badges$badge.unlock_gunner.desc=Unlock the Gunner by modifing a gun _once_
badges$badge.unlock_samurai.title=Samurai Unlocked!
badges$badge.unlock_samurai.desc=Unlock the Samurai by _getting a new katana weapon_
badges$badge.unlock_knight.title=Knight Unlocked!
badges$badge.unlock_knight.desc=Unlock the Knight by _getting a plate armor_

###v3.3.0
badges$badge.unlock_adventurer.title=Adventurer Unlocked!
badges$badge.unlock_adventurer.desc=Unlock the Adventurer by _activationg plants 10 times_

###v3.18.0
badges$badge.unlock_medic.title=Medic Unlocked!
badges$badge.unlock_medic.desc=Unlock the Medic by brewing pills _5 times_

###v3.25.0
seedfinder.found=Examined %d seeds
seedfinder.trinket=trinket
seedfinder.already_playing=There's a game with that seed already. To analyze it, you must complete the game.
seedfinder.seedfind_warning=Finding seeds. Please wait...
seedfinder.seedanalyze_warning=Analyzing the seed. Please wait...

###v3.26.0
badges$badge.hedgehog.title=The hedgehog
badges$badge.hedgehog.desc=Pinned 10 arrows on one enemy

seedfinder.error=The seedfinder did not complete the task due to unexpected error.\nPleast report screenshots that contain all texts in this screen as a github issue if you need a support.\n\n_Text Input:_\n%1$s\n\n_System Message:_\n%2$s

###v3.34.0
badges$badge.unlock_archer.title=Archer Unlocked!
badges$badge.unlock_archer.desc=Unlock the Archer by _getting a bow weapon_

###DER
rankings$record.chaosstone=Acquired %d Chaosstones

utils.dungeonseed.rat-rat-rat.desc=- All mobs (except bosses) are replaced by rats\n\n- Those rats will scale with player's progression
utils.dungeonseed.rog-ueb-uff.desc=- Replaces character's starting Cloak of Shadows with random identified artifact
utils.dungeonseed.rev-ers-eed.desc=- Changes the visuals of each region to be reversed; sewers will look like halls and halls will look like sewers
utils.dungeonseed.now-all-she.desc=- Converts walls between rooms into embers\n\n- Converts bookshelves and doors into chasms
utils.dungeonseed.rng-ite-mss.desc=- Makes items visually frequently shift into other items\n\n- This doesn't affect item functionality
utils.dungeonseed.ite-mch-est.desc=- Stores all items into dungeon into chests\n\n- Any container that is not a chest will be converted into one
utils.dungeonseed.exp-ans-ive.desc=- Increased amount of standard and special rooms by 2x\n\n- Increased amount of monsters by 2x\n\n- Increased amount of items by 1.5x
utils.dungeonseed.bes-tfr-end.desc=- Enemies have 33% chance to turn into ally, when directly hit by hero
utils.dungeonseed.ech-ech-ech.desc=- Spawns unique "ech" ally, that follows the hero and helps them in combat\n\n- Ech has 8 HP, 1-5 HP, 1-3 armor, scales with hero's progression and shares immunities with them\n\n- Ech has different effects based on hero played:\n\n- Warrior: 2x armor\n\n- Mage: attacks from any distance with 50% reduced damage\n\n- Rogue: +50% accuracy and evasion\n\n- Huntress: triggers bow's enchantment\n\n- Duelist: +50% attack speed, gets a damage boost in form of 25% damage roll of hero's weapon\n\n- Cleric: +50% health\n\n\n- When ech dies, it will trigger a food talent and respawn on the next stage
utils.dungeonseed.bob-pal-kia.desc=- Combines effects of every other seed in the list\n\n- May be unstable and impossible to properly play
utils.dungeonseed.rot-inm-ind.desc=- Gives a free kromer at start of the game\n\n- Effectively disables warp by setting its max value to 1
utils.dungeonseed.iwa-ntm-ony.desc=- Almost every item generated or dropped by mobs has to be bought with cash\n\n- Small amounts of money is generated when taking or dealing damage in any way
utils.dungeonseed.who-lep-ack.desc=- Item heaps have 25% chance to spawn another item\n\n- Mobs regenerate 1 health per 3 turns\n\n- Stores all items into dungeon into chests\n- Any container that is not a chest will be converted into one\n\n- Increased amount of standard and special rooms by 2x\n- Increased amount of monsters by 2x\n- Increased amount of items by 1.5x
utils.dungeonseed.rrr-rrr-rrr.desc=- All text is randomly changed to use letter 'R' as first letter\n\n- There is 1/15 chance for any sound to be replaced by 'R' sound with random volume and pitch\n\n- All mobs (except bosses) are replaced by rats\n- Those rats will scale with player's progression\n\n- Replaces character's starting Cloak of Shadows with random identified artifact\n\n- Changes the visuals of each region to be reversed; sewers will look like halls and halls will look like sewers
utils.dungeonseed.ama-gen-erf.desc=- Changes wand type in character's Mage's Staff into a wand type, that is not Magic Missile
utils.dungeonseed.col-los-eum.desc=- Adds a special charging blocking mechanic, when broken seal is available\n\n- It charges up depending on hero's broken seal max shielding and charge speed\n\n- Once it is charged, hero can use it to enter blocking state, where the next attack will turn into shielding instead of damaging the hero\n\n- Successful block will also increase accuracy by 2x for 3 turns\n\n- Any attack can be blocked, even magical zaps
utils.dungeonseed.buf-hun-trs.desc=- Missiles no longer become unbreakable at 100 durability and no longer fit into magical holster\n\n- Missiles can no longer proc Followup Strike\n\n- Sniper subclass no longer pierces armor\n\n- Missiles and spirit bow no longer have increased accuracy from distance
utils.dungeonseed.bet-ter-wep.desc=- Replaces hero's starting weapon with a random identified weapon, that is permanently downgraded to tier 1\n\n- The weapon is chosen out of 5 normal weapon tiers, with 1/11 chance for it to be tier 6
utils.dungeonseed.god-chi-ldd.desc=- The hero has most of cleric's innate benefits\n\n- A free Holy Tome is given at the start, that recharges at full speed\n\n- All tier 1, tier 2 and tier 3 spells are available from the start and are at their max potency
utils.dungeonseed.rng-ski-lls.desc=- All general talents are metamorphed into another set of talents
utils.dungeonseed.equ-alo-dds.desc=- All generated items start with equal weight, meaning they are all equally rare at first\n\n- Armor and weapons have equivalent odds of generating at tier 2 and tier 6, regardless of region\n\n- This also means that Scrolls of Upgrade and Potions of Strength can generate in normal pool
utils.dungeonseed.lev-eld-own.desc=- The hero starts at level 24 instead of level 1\n\n- Killing enemies makes player lose experience and levels instead\n\n- Going below level 1 is a game over
utils.dungeonseed.cor-ros-ion.desc=- The hero starts with Wand of Corrosion +100\n\n- All other weapons (including missiles, bombs and other wands) are almost absent in the dungeon
utils.dungeonseed.glo-win-ggg.desc=- All weapons (including missiles) are enchanted\n\n- All armors are enchanted\n\n- Stones of Enchantment can spawn naturally and are fairly common\n\n- Missile weapons can be manually enchanted\n\n- All items and mobs glow with randomized colors
utils.dungeonseed.rog-uel-ike.desc=- All general talents are metamorphed into another set of talents\n\n- Replaces hero's starting weapon with a random identified weapon, that is permanently downgraded to tier 1\n- The weapon is chosen out of 5 normal weapon tiers, with 1/22 chance for it to be tier 6\n\n- Changes wand type in character's Mage's Staff into a wand type, that is not Magic Missile\n\n- Replaces character's starting Cloak of Shadows with random identified artifact\n\n- Tengu drops a modified version of his mask, making hero choose random subclass instead of predetermined ones\n\n- The only available armor ability to take is Omniability
utils.dungeonseed.ult-ima-tee.desc=- All talents in the game are active at same time and are upgraded to maximum
utils.dungeonseed.sup-erm-ann.desc=- All innate class benefits are active at the same time\n\n- This doesn't include identified items or starting equipment
utils.dungeonseed.iro-nma-nnn.desc=- All subclass abilities and effects are active at the same time, when hero has obtained a subclass
utils.dungeonseed.asc-end-ant.desc=- All talents in the game are active at same time and are upgraded to maximum\n\n- All innate class benefits are active at the same time\n\n- This doesn't include identified items or starting equipment\n\n- All subclass abilities and effects are active at the same time, when hero has obtained a subclass
utils.dungeonseed.vba-lan-ced.desc=- Locks the player to Rat King\n\n- All innate class benefits are active at the same time\n\n- All subclass abilities and effects are active at the same time, when hero has obtained a subclass\n\n- Reduces player's max health from 20(+5) to 5(+3)\n\n- Adds a special charging blocking mechanic, when broken seal is available\n- It charges up depending on hero's broken seal max shielding and charge speed\n- Once it is charged, hero can use it to enter blocking state, where the next attack will turn into shielding instead of damaging the hero\n- Successful block will also increase accuracy by 2x for 3 turns\n- Any attack can be blocked, even magical zaps\n\n- Changes wand type in character's Mage's Staff into a wand type, that is not Magic Missile\n\n- Replaces character's starting Cloak of Shadows with random identified artifact\n\n- Missiles no longer become unbreakable at 100 durability and no longer fit into magical holster\n\n- Missiles can no longer proc Followup Strike\n- Sniper subclass no longer pierces armor\n- Missiles and spirit bow no longer have increased accuracy from distance\n- Huntress and Freerunner no longer have innate boost to missiles
utils.dungeonseed.fun-fun-fun.desc=- Spawns unique "ech" ally, that follows the hero and helps them in combat\n- Ech has 8 HP, 1-5 HP, 1-3 armor, scales with hero's progression and shares immunities with them\n- Ech has different effects based on hero played:\n- Warrior: 2x armor\n- Mage: attacks from any distance with 50% reduced damage\n- Rogue: +50% accuracy and evasion\n- Huntress: triggers bow's enchantment\n- Duelist: +50% attack speed, gets a damage boost in form of 25% damage roll of hero's weapon\n- Cleric: +50% health\n- When ech dies, it will trigger a food talent and respawn on the next stage\n\n- Enemies have 33% chance to turn into ally, when directly hit by hero\n\n- Gives a free kromer at start of the game\n- Effectively disables warp by setting its max value to 1\n\n- All enemies are champions, but have 33% stat reduction\n\n- All weapons (including missiles) are enchanted\n- All armors are enchanted\n- Stones of Enchantment can spawn naturally and are fairly common\n- Missile weapons can be manually enchanted\n- All items and mobs glow with randomized colors

challenges.forget_path=Shadow Curse
challenges.forget_path_desc=Something lurks in there...\n\n_-_ You quickly forget explored parts of the level\n\n_-_ Mobs can spawn from any distance and move slightly faster\n\n_-_ Your visibility is slightly reduced

challenges.no_accuracy=Predictable Battles
challenges.no_accuracy_desc=What is accuracy roll but a harmful RNG!\n\n_-_ Both enemies and player cannot dodge or miss\n\n_-_ Character gets up to _25%_ damage reduction depending on excessive evasion stat\n\n_-_ Character gets up to _25%_ damage increase depending on excessive accuracy stat\n\n_-_ Ferret Tuff is banned

challenges.random_hp=Crowd Diversity
challenges.random_hp_desc=Look at how small this cow is!\n\n_-_ Enemies in dungeon get random size\n\n_-_ Size determines their attack and movement speed, defense, evasion and melee damage\n\n_-_ Bosses and minibosses are unaffected

challenges.unstable_damage=Damage Instability
challenges.unstable_damage_desc=_-_ Taken damage is multiplied by 50%-200%, this is applied after all damage reduction effects

challenges.many_mobs=Infestation
challenges.many_mobs_desc=_-_ 4x more regular rooms\n\n_-_ 16x more monsters

challenges.no_hp=Degrading Health
challenges.no_hp_desc=No rest for careless!\n\n_-_ Half of incoming damage is converted into temporary max HP loss for 10 turns\n\n_-_ This stacks for additional 5 turns with more damage

challenges.no_levels=Uninspired to Learn
challenges.no_levels_desc=_-_ Enemies do not drop XP\n\n_-_ Bosses (including abyssal) instantly raise your level by 1 after defeat

utils.warppile$degradeeffect.message=Your equipment is weakened by dark magic...
utils.warppile$vertigoeffect.message=You feel disoriented...
utils.warppile$vulnerableeffect.message=Your physique is weakened...
utils.warppile$scameffect.message=The voices whisper about lower prices...
utils.warppile$adrenalineeffect.message=Your wrath manifests with high energy...
utils.warppile$fireeffect.message=The spark of your rage becomes too hot to handle...
utils.warppile$blindnesseffect.message=Your vision suddenly dims...
utils.warppile$antimagiceffect.message=The magical items in your hands are suppressed...
utils.warppile$sloweffect.message=You briefly slow down to think about your actions...

utils.warppile$coldeffect.message=The deadly cold catches your lungs...
utils.warppile$visioneffect.message=Your vision suddenly expands...
utils.warppile$shrinkeffect.message=The world grows larger around you...
utils.warppile$regrowtheffect.message=The weeds erupt at your feet...
utils.warppile$hungereffect.message=You feel like you haven't eaten for ages...
utils.warppile$spawneffect.message=Something is coming...
utils.warppile$retributioneffect.message=Your inner stress is finally released...
utils.warppile$warpcleareffect.message=Your mind finally gets clear...
utils.warppile$empowereddegradeeffect.message=Your equipment is reduced to nothing by dark magic...

utils.warppile$summoneffect.message=Creatures you have never seen before emerge from the shadows...
utils.warppile$warpingeffect.message=All good memories about this floor are fading away...
utils.warppile$empoweredspawneffect.message=The entire dungeon is after you...
utils.warppile$cursingeffect.message=Your equipment is corrupted by dark magic...
utils.warppile$crazybanditeffect.message=The dark magic backstabs you from shadows...
utils.warppile$rechargeeffect.message=The massive surge of energy overwhelms you...